GET http://localhost:5000/user

### Signup

POST https://damian-backend.vercel.app/signup
Content-Type: application/json

{
    "firstname": "Damian",
    "lastname": "Chidera",
    "email": "chideralawrence500@gmail.com",
    "password": "damianShot"
}

### Login

POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "almin@gmail.com",
    "password": "alminShot"
}

### Get All Messages

GET http://localhost:5000/getMessages
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjAxMGQ5NjhkMzA3NGE3N2M2YWJlOTQiLCJpYXQiOjE3MTEzNDUwNDl9.hcB59LEdTZAkXPrXjlmdsZBGEbkgFS9qW3MGNB9-SEI



### Post Message

POST http://localhost:5000/messages
Content-Type: application/json

{
    "clientEmail": "olaLoveBeans@gmail.com",
    "clientMsg": "To integrate the login functionality with the provided UI, you need to add event handlers for input changes and form submission. Then, you'll dispatch the logUser action creator when the form is submitted. Here's how you can modify the UI"
}

### Post images
POST http://localhost:5000/addPhoto
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjAxMGQ5NjhkMzA3NGE3N2M2YWJlOTQiLCJpYXQiOjE3MTEzNDUwNDl9.hcB59LEdTZAkXPrXjlmdsZBGEbkgFS9qW3MGNB9-SEI

{
    "imgUrl": "https://assets.vogue.com/photos/6345c499b233071b4e23de2f/master/w_320%2Cc_limit/00023-moschino-spring-2023-ready.jpeg"
}

### Delete images
DELETE http://localhost:5000/deleteImages/65f75dd08bf8e337ca82021b

### Get images
GET http://localhost:5000/viewImages